name: Build binaries

on:
  push:
    branches: [ master ]

jobs: 
  build-linux:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Install compilers
        run: |
          sudo apt update ; sudo apt install -y gcc-mingw-w64-i686 gcc-mingw-w64-x86-64

      - name: Compile
        run: |
          ./bundle_calibre_plugin.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with: 
          name: linux
          path: |
            calibre-plugin.zip
    
  test-linux:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install freezegun lxml pycryptodome rsa oscrypto

      - name: Run tests
        run: |
          cd tests && ./main.py

